### ISSUE TITLE
Connectors startup error

### ISSUE THREAD

**Issue by erikh360** [praekeltfoundation/vumi2#52]
When starting up a ToAddressRouter while messages are being processed, the connectors are started as they are created here:
https://github.com/praekeltfoundation/vumi2/blob/main/src/vumi2/routers.py#L43-L57

The problem is that the outbound connector is started and processing messages before the inbound connector exists.

This causes a key error when we try and publish the message to the transport.

**Comment by rudigiesler** [comment]
Thanks for finding this. In vumi v1 there was a system to "pause" connectors while everything was being started, and then unpause them once startup had completed.

So either we need something like that, or maybe there's a different way we can do this, maybe by changing the order in which things are started.

**Comment by jerith** [comment]
Changing the order of connector setup will just move the problem from outbound to inbound.

I think our best bet would be to split `Consumer.start()` into a `.setup()` method that creates the channel does the exchange/queue stuff and a `.start()` method that calls `channel.basic_consume()` and starts the handler tasks. Then we'd call `consumer.setup()` in `Connector._setup_consumer()` and add a `Connector.start_consuming()` method (or similar) to call `consumer.start()` when we're actually ready to handle messages.

Another (easier) option would be to leave `Consumer.start()` as-is and just move the call to `Connector.start_consuming()` (or whatever we call it).

Either way, we can put a helper method on `ConnectorCollection` to start all the consumers together, like we already do there for cleanup.

Thoughts?

**Comment by erikh360** [comment]
@jerith I don't have enough knowledge on vumi2 to give a useful opinion on your comment but I I'm going to give the first option a go to see how it goes.

**Comment by jerith** [comment]
Having had a look at the code, I think the trickiest part will be writing a test that fails reliably for this. I'll try prototype that quick.

**Comment by jerith** [comment]
Fixed in #53.
